# Generated by Django 5.2.2 on 2025-06-12 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('a_users', '0002_remove_profile_image_profile_featured_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='featured_image',
            new_name='image',
        ),
    ]
